### PR TITLE
Changes file extension of public facing files from .h to .hpp

### PR DESCRIPTION
**Pull request by OlekRaymond**
The generally accepted assumptions are:
- `.h` is the file extension for C header files
- `.hpp` is the file extenstion for C++ header files

Currently all the C++ headers are marked as C header files. This makes it a little more confusing for tooling and people to understand how the code is intended to be used.

I have only made changes for files that are often user facing to minimise problems

More information is provided by [Jason Turner](https://www.youtube.com/watch?v=mr3sOT-Delg)

### CODE REVIEW

**Comment by austinvhuang** [comment]
This is reasonable to me, esp we may have some legit C header files for ABI interfaces in the future. It touches a lot of surface area, so I think we'll target it to the dev branch, merge and work out any kinks there before merging to main.

**Comment by OlekRaymond** [comment]
Shall do, thanks :)

**Comment by OlekRaymond** [comment]
@austinvhuang Did you want a new pull request or is the automatic rebase from github good?

**Comment by austinvhuang** [comment]
@OlekRaymond if you can resolve the merge conflicts we can go ahead and merge to the dev branch, either way works.

**Pull request merged**
